export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INITIAL_INGREDIENTS = 'SET_INITIAL_INGREDIENTS';
export const SET_INITIAL_INGREDIENTS_FAILED = 'SET_INITIAL_INGREDIENTS_FAILED';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const PURCHASE_INITIATE = 'PURCHASE_INITIATE';
export const INITIATE_PURCHASE_BEFORE_REDIRECT = 'INITIATE_PURCHASE_BEFORE_REDIRECT';


export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT'; // loading


export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATION_SUCCESS  = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_INITIATE = 'AUTHENTICATION_INITIATE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'